version: "3"
services:
  react-app:
    image: react-app-production:local
    restart: unless-stopped
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - mern-app
  api-server:
    image: api-server
    restart: unless-stopped
    env_file: ./GroomRoom-server/config/local.env
    ports:
      - "6060:6060"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
   driver: local