version: "3"
services:
  react-app:
    image: react-app-dev
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./GroomRoom-client/:/usr/src/app
      - /usr/src/app/node_modules
  api-server:
    image: api-server
    build: ./GroomRoom-server/
    ports:
      - "6060:6060"
    networks:
      - mern-app
    volumes:
      - ./GroomRoom-server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local