version: "3.7"
services:
  react-app:
    image: react-app-production:production
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports: 
      - "80:80"
      - "443:443"
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: api-server
    restart: unless-stopped
    env_file: ./GroomRoom-server/config/production.env
    ports:
      - "6060:6060"
    networks:
      - mern-app 
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local