FROM node:alpine

RUN apk add g++ make py3-pip

WORKDIR /usr/src/app

COPY ./package.json ./

RUN npm install

COPY . .

ENV REACT_APP_BASE_URL=http://188.166.112.233:6060
ENV REACT_APP_WS_URL=ws://188.166.112.233:6060/
ENV REACT_APP_BASE_DOMEN=http://188.166.112.233:80

CMD [ "npm", "start" ]