FROM node:alpine

RUN apk add g++ make py3-pip

WORKDIR /usr/src/app

COPY ./package.json ./

RUN npm install

COPY . .

ENV REACT_APP_BASE_URL=http://178.62.214.111:6060
ENV REACT_APP_WS_URL=ws://178.62.214.111:6060/
ENV REACT_APP_BASE_DOMEN=http://178.62.214.111:3000

CMD [ "npm", "start" ]